name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -p:Platform="x86"
    - uses: actions/upload-artifact@v2
      with:
        name: OZEdit-Cmd-x86-debug
        path: OZEdit/bin/x86/Debug/netcoreapp3.1
    - uses: actions/upload-artifact@v2
      with:
        name: OZEdit-GUI-x86-debug
        path: MapPublishingApp/bin/x86/Debug/netcoreapp3.1
